### ISSUE TITLE
ReactCompositeComponent: injectEnvironment() can only be called once.

### ISSUE THREAD

**Issue by clozr** [apentle/react-native-babel-jest#1]
I encountered this error when using react-test-renderer.
Any idea how it can be fixed?

**Comment by clozr** [comment]
I figured that your package is set to use enzyme instead of react-test-renderer.

**Comment by doanndd** [comment]
FYI, I used `react-native-mock` with `react-addons-test-utils` from file `env.js`. If you want to use with `react-test-renderer`, you can add this code `jest.mock('react-addons-test-utils');` to `env.js`.

More about this error, you can find in https://github.com/facebook/jest/issues/1353

Thank you.

**Comment by clozr** [comment]
You are using locally cached version of react-native-mock, which doesn't work with latest react-native. I changed the mock in env.js
`jest.setMock('react-native', require('react-native-mock/src/react-native'));` 

Which makes it work.

**Comment by doanndd** [comment]
I updated to latest `react-native-mock` version. You should rerun `npm i react-native-babel-jest`.
Thanks!

**Comment by clozr** [comment]
Cool Thanks!
I think in your examples you should include an example of snapshot testing using enzyme-to-json. Someone looking to use snapshot testing will know that they don't need react-test-renderer.

**Comment by doanndd** [comment]
Thank you,
I'm doing it now.
